// The AppHost is the Aspire entry point — think of it as infrastructure-as-code
// expressed in C# rather than YAML or Terraform. It declares what services exist,
// how they relate to each other, and what resources they need.
//
// When you run this project:
//   1. Aspire launches the Aspire Developer Dashboard (http://localhost:15000)
//   2. It starts WatcherNet.Silo, WatcherNet.Api, and WatcherNet.Dashboard as managed child processes
//   3. It injects environment variables (ports, OTEL endpoints, connection strings) automatically
//   4. All logs, traces, and metrics from all services flow to the dashboard in real time

var builder = DistributedApplication.CreateBuilder(args);

// AddProject<T>() tells Aspire to manage this project as a service.
// The generic type (Projects.WatcherNet_Silo) is generated by the Aspire SDK
// from the ProjectReference in this .csproj — no magic strings.
var silo = builder.AddProject<Projects.WatcherNet_Silo>("silo");

var api = builder.AddProject<Projects.WatcherNet_Api>("api")
    // WithReference propagates the silo's address to the API via environment variables.
    // The API doesn't need a config file entry for the silo address — Aspire handles it.
    .WithReference(silo)
    // WithExternalHttpEndpoints makes the API's port accessible from outside the Aspire process.
    .WithExternalHttpEndpoints();

// Blazor Server dashboard — Aspire injects the API URL via service discovery.
// The Dashboard never talks to Orleans directly; it only speaks HTTP to the API.
// WithReference(api) means the Dashboard knows where the API is — no config needed.
builder.AddProject<Projects.WatcherNet_Dashboard>("dashboard")
    .WithReference(api)
    .WithExternalHttpEndpoints();

builder.Build().Run();
